services:
  dayz-server:
    #Uncomment when you need to run container user as root
    #user: "0:0"
    # 1. Point to your Dockerfile
    build:
      context: .           # The directory containing the Dockerfile
      dockerfile: Dockerfile
    # 2. Resource requests and limits
    deploy:
      resources:
        limits:
          cpus: 6
          memory: 8g
        reservations:
          cpus: 6
          memory: 8g
    # 3. Give your container a recognizable name
    container_name: dayz-test-server
    # 4. These Folders need to be mounted on host machine
    volumes:
      - ./data:/home/dayz-docker
    # 5. Expose the essential UDP ports to your local network
    ports:
      - "2301-2307:2301-2307/udp"
      - "27016:27016/udp"
    # 6. Environemntal variables
    environment:
      STEAM_USERNAME: "steam_username"
      STEAM_PASSWORD: "steam_password"
      PORT: 2302 #default port
    # Optional: ensure it restarts if it crashes
    restart: unless-stopped
